- src/models/AnalyticsEventType.ts
- src/models/events/AnalyticsEvent.ts
- src/models/events/PaginationEvent.ts
Add event type for PAGINATE for pagination interactions.
J=SLAP-1822
TEST=manual
see 200 status from PAGINATE event fires in test-site.
> add pagination event

- package-lock.json
- package.json
- src/index.ts
- src/models/AnalyticsEventType.ts
- src/models/events/AnalyticsEvent.ts
- src/models/events/SearchClearEvent.ts
Add event type for SEARCH_CLEAR_BUTTON and export AnalyticsService.
J=SLAP-1820
TEST=manual
Check that event fires correctly from test-site.
> Add Search Clear Event

- package.json
- src/models/AnalyticsEventType.ts
- src/models/events/AnalyticsEvent.ts
- src/models/events/AutocompleteEvent.ts
- test-site/package-lock.json
add autocomplete analytics event for when user select an autocomplete suggestion
J=SLAP-1821
TEST=manual
use analytics test-site to fire an `AUTO_COMPLETE_SELECTION` event and see 200 status.
> add autocomplete analytics event

- package-lock.json
- package.json
- src/models/AnalyticsEventType.ts
- src/models/events/AnalyticsEvent.ts
- src/models/events/CtaEvent.ts
- src/models/events/SearchClearEvent.ts
- src/models/events/VerticalViewAllEvent.ts
- test-site/package-lock.json
Add event type for VERTICAL_VIEW_ALL.
J=SLAP-1823
TEST=manual
Check that the event fires correctly from the test-site with 200 status.
> Add vertical view all event

- package-lock.json
- package.json
will publish a beta after merging
J=NONE
> track src in npm for sourcemaps

- package.json
This PR adds a list of approved keywords to package.json and updates Answers to Search in description.
J=SLAP-2190
TEST=manual
> update description to Search and add list of approved keywords

- package-lock.json
- package.json
Bump the version number to v0.5.0 which includes EU support
> Version 0.5.0

- src/AnalyticsConfig.ts
Create AnalyticsConfig interface.
J=FUS-5867
TEST=auto
> EventsSDK: create AnalyticsConfig interface

- src/AnalyticsEventService.ts
Create AnalyticsEventService interface that will be implemented by AnalyticsEventReporter.
J=FUS-5868
TEST=auto
> EventsSDK: create AnalyticsEventService

- package-lock.json
- test-site/package-lock.json
Pixels: Update Package lock
We forgot to update this file when we merged the package.json update. Ran
```
npm i
cd test-site
npm i
```
to regenerate both of them.
> Fix Packagelock.json

- src/AnalyticsEventReporter.ts
This function returns a new instance of AnalyticsEventReporter with the same config but with the EventPayload applied.
J=FUS-5872
TEST=auto
The logic inside with() function is simple: As long as merge() and the constructor work, it should work. So I did not write tests for it.
> Implement with() Function

- .github/workflows/deploy_hold.yml
- .gitignore
- package-lock.json
- package.json
- src/index.ts
- test-cdn/index.html
- vite.config.ts
Following the instructions provided [here](https://yext.slack.com/archives/G01SSAYJVM4/p1693430423898279), added the necessary files so the library can be deployed to CDN via github actions
J=FUS-5877
TEST=manual
Added a test cdn site that mirrors the test site. Replaced all instances of `%YEXT_API_KEY%` with an actual API key, and verified that clicking the button resulted in 2xx responses.
> Configure Library to be deployed to CDN via Actions

- README.md
Make a few small fixes to the readme.
- lowercase `a` in analytics import
- no `new` when invoking
- remove appendix
- add missing coma
J=FUS-5897
R=abenno, mtian
TEST=none
> EventsSdk: Update ReadMe

- .github/workflows/playwright.yml
- .github/workflows/run_tests.yml
- .gitignore
- package-lock.json
- package.json
- playwright.config.ts
- test-e2e/example.spec.ts
- tests-examples/demo-todo-app.spec.ts
Ran npm init playwright@latest and edited the github action file to suit our needs.
J=FUS-5879
TEST=auto
Pushed change and verified that new action is listed. Also, verified that the `run_tests` action only runs `npx jest`
> EventsSDK: Create New Playwright GH Action

- test-site/src/index.ts
Update queryId and searchId params in Test Site to match expected pattern.
R=mtian, hyu
TEST=manual
Ran test site and there was a successful response for the Send Search Event buttonEventsSDK: Update Search Params in Test Site
> EventsSDK: Update Search Params in Test Site

- package-lock.json
- package.json
- test-site/package-lock.json
- tests/AnalyticsEventReporter.test.ts
Bump 1.0.0-beta.0 -> 1.0.0-beta.1 in package.json and package-lock.json
> EventsSDK: Bump Version

- .github/workflows/build_and_deploy_hold.yml
Change .yml -> .yaml for extract_version
> EventsSDK hotfix: Fix extract_version action reference

- README.md
After updating how authorization tokens are passed into AnalyticsConfig, we need to update the ReadMe to reflect the change.
> EventsSDK: Update ReadMe with new AnalyticsConfig

- package-lock.json
- package.json
- test-site/package-lock.json
- tests/AnalyticsEventReporter.test.ts
> EventsSDK: Bump version to v1.0.0-beta.4

- package-lock.json
- package.json
- test-site/package-lock.json
- tests/AnalyticsEventReporter.test.ts
> EventsSDK: Bump version to 1.0.0-beta.5

- .github/workflows/build.yml
- .github/workflows/deploy_hold.yml
- .github/workflows/main.yml
- .github/workflows/playwright.yml
- .github/workflows/should_deploy_major_version.yml
This PR upgrades various github actions from their deprecated v3 versions to v4.
> analytics: upgrade github actions

- package-lock.json
- package.json
- test-site/package-lock.json
- tests/AnalyticsEventReporter.test.ts
Release version 1.0.0 based from 1.0.0-beta.8.
> EventsSDK: Release version 1.0.0

- package-lock.json
- package.json
- test-site/package-lock.json
- tests/AnalyticsEventReporter.test.ts
Update rollup for https://yexttest.atlassian.net/browse/VULN-39515
and then increase SDK version to 1.0.1
> EventsSDK: Update rollup version and release v1.0.1

- .github/workflows/build.yml
- .github/workflows/deploy_hold.yml
- .github/workflows/extract_versions.yaml
- .github/workflows/should_deploy_major_version.yml
- package-lock.json
- package.json
- test-site/package-lock.json
- tests/AnalyticsEventReporter.test.ts
Fixed potential run shell injection vulnerabilities
Increased SDK version to 1.0.2
> EventsSDK: fix run vulnerabilities
